### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DanyTPG** [luzeagithub/google-drive-index-worker#1]
Amazing minimalistic design I love your index. 
Can you also make a branch for deployment under cloudflare pages since they don't have requests limit like workers? 
Is it possible?

**Comment by luzeagithub** [comment]
No, Cloudflare Pages is for static site generators like Jekyll and Hugo. It’s not for serverless applications.

PS: Remove the copyrighted content from your drive or you’ll get in trouble.

**Comment by DanyTPG** [comment]
Thanks for answering so fast.
