### ISSUE TITLE
s.a. support not working

### ISSUE THREAD

**Issue by kokoamartin** [luzeagithub/google-drive-index-worker#2]
please consider s.a. support for the index

**Comment by luzeagithub** [comment]
I'm currently not planning to add support for that, because I don't have the time needed for testing. If you or someone else want to add it to the script, then please create a pull request for it and I'll review it.

**Comment by DanyTPG** [comment]
> please consider s.a. support for the index

The index already supports service accounts.
I'm using service accounts right now.
