### ISSUE TITLE
Assets cdn down?

### ISSUE THREAD

**Issue by DanyTPG** [luzeagithub/google-drive-index-worker#4]
Hi. Is cdn.luzea.ovh down or is it just me? The website doesn't seem to open completely.
why don't you use jsdelivr for every asset when you already have everything there?

**Comment by luzeagithub** [comment]
hi, that's exactly what i did 6 days ago: https://github.com/luzeagithub/google-drive-index-worker/commit/d4198cb20e9993b2f5ce28003cbde798f9d07dfb
