### ISSUE TITLE
Errors while loading the page

### ISSUE THREAD

**Issue by DanyTPG** [luzeagithub/google-drive-index-worker#5]
Sometimes I get these 2 errors while loading the page

> "HTTPError:` Forbidden\n    at responseErrorThrower (worker.js:183:32)\n    at async GoogleDrive.listFolder (worker.js:2618:30)\n    at async handleRequest (worker.js:2931:17)"

And

>"TypeError: Cannot destructure property 'files' of '(intermediate value)' as it is null.\n    at handleRequest (worker.js:2930:17)"

They have been happening way more often lately and the only way to load the page is by refreshing multiple times.

**Comment by DanyTPG** [comment]
Seems like using service accounts will fix this problem.

**Comment by VoXaN24** [comment]
> Seems like using service accounts will fix this problem.

How u use a S.A I have try and no file ...

**Comment by VoXaN24** [comment]
> > > Seems like using service accounts will fix this problem.
> > 
> > How u use a S.A I have try and no file ...
> 
> What do you mean "I have try and no file" ?
> Explain properly.
> 
> If you look at the worker.js file you will see
> ```
> service_account: false,
> service_account_json: {},
> ```
> 
> You basically set these two and you're good to go

Like I would use one, and when I set it up, I don't have any file show

**Comment by DanyTPG** [comment]
> Like I would use one, and when I set it up, I don't have any file show
Are you using personal drive or shared drive?
If you use shared drive did you add the drive to the S.A. ?
Did you change `service_account` variable to `true` ?

**Comment by VoXaN24** [comment]
How i add the Shared drive to the S.A ?

**Comment by DanyTPG** [comment]
> How i add the Shared drive to the S.A ?

Step 4 from this repo: 
https://github.com/xyou365/AutoRclone

**Comment by VoXaN24** [comment]
Thank's !

**Comment by DanyTPG** [comment]
> Thank's !

No worries!

**Comment by DanyTPG** [comment]
> I can add more than one account btw ?

What account?
S.A?
I haven't tried multiple S.A in the config. But you can have multiple S.A for a shared drive.

**Comment by DanyTPG** [comment]
> Yes S.A Account, idk how set it up in the file

The repo is quite self-explanatory.
You make the S.A. add the shared drive access to them. then you will have a json file which contains the S.A. you add that json in the worker.js file.

Can't help you furthermore

**Comment by jasprivate194** [comment]
Hi

W dniu 2021-05-28 14:06 użytkownik "DanyTPG" ***@***.***>
napisał:

> Yes S.A Account, idk how set it up in the file

The repo is quite self-explanatory.
You make the S.A. add the shared drive access to them. then you will have a
json file which contains the S.A. you add that json in the worker.js file.

Can't help you furthermore

**Comment by VoXaN24** [comment]
> > Yes S.A Account, idk how set it up in the file
> 
> The repo is quite self-explanatory.
> You make the S.A. add the shared drive access to them. then you will have a json file which contains the S.A. you add that json in the worker.js file.
> 
> Can't help you furthermore

Yes but for add a 2nd SA, i just past the seconde json file ?

**Comment by DanyTPG** [comment]
> Yes but for add a 2nd SA, i just past the seconde json file ?

As I said I haven't tried multiple S.A in the worker file.
